server: 
  port: 3344 
  jetty: 
    acceptors: 2
    selectors: 2
  
spring:
  application:
    name:  comicgrab-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenmaochang/microservicecloud-config.git